version: '3.3'
services:
 db:
 image: mysql:5.7
 volumes:
 - db_data:/var/lib/mysql
 restart: always
 environment:
 MYSQL_ROOT_PASSWORD: todopassword
 MYSQL_DATABASE: todo
 MYSQL_USER: todo
 MYSQL_PASSWORD: todo
 todo:
 depends_on:
 - db
 image: littlekhung/todo:latest
 ports:
 - "3000:3000"
 restart: always
volumes:
 db_data: {}
